
# 文章评分系统
 # widgetpack。将 false 改为 widgetpack 上的 id 则启用该评论系统。
 # Star rating support to each article.
 # To get your ID visit https://widgetpack.com
widgetpack:
  enable: false #false
  id: 30332 #<app_id>
  color:  fc6423

# title
title: 星云网赚

# 来必力评论系统
# livere配置
livere:
  enable: false
  uid: MTAyMC81MzA1OS8yOTUzNQ==

# Twikoo
# 基于腾讯云开发
# Based on Tencent CloudBase
# See: https://twikoo.js.org
twikoo:
  enable: true
  envId: https://www.nothinglintwikoo.ml/

# tawk在线聊天系统
tawk:
  enable: false

# tidio在线聊天系统
tidio:
  enable: false

# Chatra在线聊天系统
chatra:
  enable: false

# 博客brand设置
blogTitle:
  bigtitle: "星云网赚"
  subtitle: "敬每个年入百万的梦想"

# 个人信息介绍栏
aboutAuthor: "关于 星云网赚"
AuthorInfo: "敬每个年入百万的梦想"

## Feed
rss: /atom.xml
## favicon
favicon:

# 文章日历
# Whether to display post-calender in the `archive` page
# 设置在归档页面achive中是否显示'文章日历'控件
# 仿GitHub贡献条
postCalendar: false
js:
  echarts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
